from dataclasses import dataclass
from pathlib import Path
from typing import Literal

import numpy as np
from marlenv import Observation
from torch import device

from marl.models import Action, Agent

from .spec import HavenSpec


@dataclass
class Haven(Agent):
    """
    Hierarchical agent where a meta-agent gives orders (i.e. actions, subgoals, communication) to workers (multi-agent).

    The subgoals are concatenated to the worker's observations as "extras".
    """

    meta: Agent
    workers: Agent
    n_subgoals: int
    k: int
    """The number of steps that meta-actions lasts."""

    def __init__(
        self,
        meta_agent: Agent,
        workers: Agent,
        n_subgoals: int,
        n_workers: int,
        k: int,
        n_meta_extras: int,
        n_agent_extras: int,
        *,
        use_previous_meta_action: bool = True,
    ):
        """Initialize the two policy timescales and optional macro-action history. @ai-edited"""
        super().__init__()
        self.spec = HavenSpec(n_workers, n_subgoals, k, n_meta_extras, n_agent_extras, use_previous_meta_action)
        self.meta = meta_agent
        self.workers = workers
        self.k = k
        self.n_subgoals = n_subgoals
        self._t = 0
        self.last_meta_action = np.zeros(0, dtype=np.int64)
        self.last_subgoals = np.zeros(0, dtype=np.float32)
        self.n_meta_extras = n_meta_extras
        self.n_agent_extras = n_agent_extras
        self.n_workers = n_workers
        self.use_previous_meta_action = use_previous_meta_action
        self._train_context = None

    def choose_action(self, observation: Observation, *, with_details: bool = False):
        """
        In HAVEN, the workers take an action at each step, but the meta-agent takes an action every k steps.

        The subgoals generated by the meta-agent are put into the "extras" of the workers.
        """
        assert observation.extras_shape[0] == self.n_meta_extras + self.n_agent_extras + self.n_subgoals
        if self._t % self.k == 0:
            meta_obs = self.make_meta_observation(observation)
            meta_action = self.spec.validate_action(self.meta.choose_action(meta_obs, with_details=with_details).action)
            subgoals = self.spec.encode_goal(meta_action)
            self.last_meta_action = meta_action
            self.last_subgoals = subgoals
        self._t += 1
        worker_obs = self.spec.worker_observation(observation, self.last_meta_action)
        workers_actions = self.workers.choose_action(worker_obs, with_details=with_details)
        details = workers_actions.details | {"meta_actions": self.last_meta_action.copy()}
        return Action(workers_actions.action, **details)

    def make_meta_observation(self, observation: Observation):
        """Build macro inputs without exposing a mutable view of environment extras. @ai-edited"""
        previous = self.last_meta_action if self._t else None
        return self.spec.meta_observation(observation, previous)

    def new_episode(self):
        """Reset both policies and their active macro action. @ai-edited"""
        self.workers.new_episode()
        self.meta.new_episode()
        self._t = 0
        self.last_meta_action = np.zeros(0, dtype=np.int64)
        self.last_subgoals = np.zeros(0, dtype=np.float32)

    def set_testing(self):
        """Preserve the complete training macro context during evaluation. @ai-edited"""
        if self.is_testing:
            return
        self._train_context = (self._t, self.last_meta_action.copy(), self.last_subgoals.copy())
        self.meta.set_testing()
        self.workers.set_testing()
        self._training = False
        self._t = 0

    def set_training(self):
        """Restore training goals as well as child recurrent histories. @ai-edited"""
        if self.is_training:
            return
        self.meta.set_training()
        self.workers.set_training()
        self._training = True
        if self._train_context is not None:
            self._t, self.last_meta_action, self.last_subgoals = self._train_context

    def networks(self):
        return self.meta.networks() + self.workers.networks()

    def save(self, to_directory: Path):
        self.meta.save(to_directory / "meta")
        self.workers.save(to_directory / "worker")

    def load(self, from_directory: Path):
        self.meta.load(from_directory / "meta")
        self.workers.load(from_directory / "worker")

    def to(self, device: device):
        self._device = device
        self.meta.to(device)
        self.workers.to(device)
        return self

    def randomize(self, method: Literal["xavier", "orthogonal"] = "xavier"):
        self.meta.randomize(method)
        self.workers.randomize(method)
