[tool.poetry]
name = "marl"
version = "0.1.0"
description = "Multi Agent Reinforcement Learning algorithms with the RLEnv library"
authors = ["Yannick Molinghen <yannick.molinghen@ulb.be>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10, <3.13"
torch = "^1.13.1"
numpy = "^1.23.4"
rlenv = { git = "https://github.com/yamoling/rlenv.git" }
tensorboard = "^2.11.2"
opencv-python = "^4.7.0.68"
sumtree = "^0.2"
polars = "^0.16.18"
tqdm = "^4.65.0"
argcomplete = "^3.0.8"
pynvml = "^11.5.0"
lle = { git = "https://github.com/yamoling/lle" }
scipy = "^1.11.3"
psutil = "^5.9.5"
gymnasium = { extras = ["box2d"], version = "^0.29.1" }
pyserde = "^0.12.3"
networkx = "^3.1"

[tool.poetry.group.dev.dependencies]
matplotlib = "^3.6.3"
websockets = "^10.4"
flask = "^2.2.2"
flask-cors = "^3.0.10"
pytest = "^7.3.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]


[tool.ruff]
# Check https://beta.ruff.rs/docs/rules/ for all rules
fixable = ["ALL"]

unfixable = [
    "F401", # Do not fix imports automatically (it removes unused imports in __init__.py files)
    "F841", # Do not fix unused variables automatically
]
line-length = 140
