[project]
name = "marl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11,<4"
dependencies = [
    "laser-learning-environment>=2.0.0",
    "python-dotenv>=1.0.1",
    "tqdm>=4.66.5",
    "scipy>=1.14.1",
    "sumtree>=0.2.7",
    "polars>=1.5.0",
    "torch>=2.4.0",
    "neptune>=1.10.4",
    "matplotlib>=3.9.2",
    "flask>=3.0.3",
    "websockets>=12.0",
    "icecream>=2.1.3",
    "typed-argparse>=0.3.1",
    "flask-cors>=4.0.1",
    "seaborn>=0.13.2",
    "multi-agent-rlenv>=2.0.0",
    "jupyterlab>=4.2.5",
    "scikit-learn>=1.5.2",
    "monte-carlo-tree-search>=2.0.5",
    "pygame>=2.6.1",
    "altair[all]>=5.5.0",
    "orjson>=3.10.12",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = ["pytest>=8.3.2", "pytest-xdist>=3.6.1"]


[tool.uv.sources]


[tool.ruff]
line-length = 140
