[tool.poetry]
name = "marl"
version = "0.1.0"
description = "Multi Agent Reinforcement Learning algorithms with the RLEnv library"
authors = ["Yannick Molinghen <yannick.molinghen@ulb.be>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
numpy = "^1.23.4"
rlenv = { git = "https://github.com/yamoling/rlenv.git" }
laser-env = { git = "https://github.com/raphaelavalos/laser-env.git" }
opencv-python = "^4.7.0.68"
tqdm = "^4.65.0"
pynvml = "^11.5.0"
scipy = "^1.11.3"
psutil = "^5.9.5"
pyserde = "^0.12.3"
networkx = "^3.1"
sumtree = "^0.2.4"
laser-learning-environment = "^0.1.10"
typed-argparse = "^0.3.1"
polars = "^0.20.6"


[tool.poetry.group.dev.dependencies]
matplotlib = "^3.6.3"
websockets = "^10.4"
flask = "^2.2.2"
flask-cors = "^3.0.10"
pytest = "^7.3.1"
pytest-xdist = "^3.4.0"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
# The number of cores to run the tests with (xdist extension)
addopts = "-n 4"


[tool.ruff]
# Check https://beta.ruff.rs/docs/rules/ for all rules
fixable = ["ALL"]

unfixable = [
    "F401", # Do not fix imports automatically (it removes unused imports in __init__.py files)
    #"F841", # Do not fix unused variables automatically
]
line-length = 140
