[tool.poetry]
name = "marl"
version = "0.1.0"
description = "Multi Agent Reinforcement Learning algorithms with the RLEnv library"
authors = ["Yannick Molinghen <yannick.molinghen@ulb.be>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10, <3.11"
torch = "^1.13.1"
numpy = "^1.23.4"
rlenv = {git = "https://github.com/yamoling/rlenv.git"}
sumtree = "^0.1.5"
tensorboard = "^2.11.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
