[tool.poetry]
name = "marl"
version = "0.1.0"
description = "Multi Agent Reinforcement Learning algorithms with the RLEnv library"
authors = ["Yannick Molinghen <yannick.molinghen@ulb.be>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.10, <4"
numpy = "^1.23.4"
rlenv = { path = "/home/yamoling/rlenv", develop = true }
tensorboard = "^2.11.2"
opencv-python = "^4.7.0.68"
laser-env = { path = "/home/yamoling/laser-env" }
sumtree = "^0.2"
polars = "^0.20"
tqdm = "^4.65.0"
argcomplete = "^3.0.8"
pyserde = "^0.12"

[tool.poetry.group.dev.dependencies]
websockets = "^10.4"
flask = "^2.2.2"
flask-cors = "^3.0.10"
pytest = "^7.3.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.pytest.ini_options]
pythonpath = ["src"]


[tool.pyright]
typeCheckingMode = "basic"       # "strict", "off"
include = ["src"]
reportPrivateImportUsage = false


[tool.ruff]
# Line length is 120 characters
line-length = 120
