width = 10 # Optional, deduced from `world_string`
height = 5 # Optional, deduced from `world_string`
exits = [{ j_min = 9 }]
gems = [{ i = 0, j = 2 }]
starts = [{ row = 2 }] # All tiles on row=2 are start positions for all agents
world_string = '''
X . . . S1 . . . . .
. . . . .  . . . . .
. . . . .  . . . . .
. . . . .  . . . . .
. . . . S2 . . . . .
'''

[[agents]]
# Define a rectangle of possible start positions with both ends included.
# The default minimal value is 0.
# The default maximal value is the width (for j) or height (for i) of the map.
starts = [{ i_min = 0, i_max = 2 }] # Rectangle from (0, 0) to (2, 4) included

[[agents]]
# Deduced from the string map that agent 1 has a start position at (0, 5).

[[agents]]
# Can either start on the 2nd row or on the 7th column.
starts = [{ row = 2 }, { col = 7 }]

[[agents]]
# Start positions can be a mix of rectangles, rows, columns and positions.
starts = [
    { i = 4, j = 9 },
    { i_min = 1, i_max = 3, j_min = 0, j_max = 3 },
    { j_min = 4 },
]
