starts = [{ i_max = 3, j_min = 2 }]
n_agents = 4

world_string = """
  G   .  . . S0 S1 S2 S3 . . . .  . 
  .   .  . . .  .  .  .  . . . .  .   
  .   .  . . .  .  .  .  . . . .  .   
  @   @  . . .  .  .  .  . . . .  .   
  .   .  . . .  .  .  @  @ @ @ @  @   
  .   .  . . .  .  .  .  . . . .  .   
  .   .  . . .  .  .  .  . . . .  . 
  .   .  . . .  .  .  @  . G . .  .   
  .   .  . . .  .  .  @  @ @ @ @  @   
  .   .  . . .  .  .  .  . . . .  .   
  .   .  . . G  .  .  .  . . X X  .   
  .   .  . . .  .  .  .  . . X X  G"""
