starts = [{ i_max = 3, j_min = 2 }]
n_agents = 4

world_string = """
  G  L2S . . .  .  .  .  . . . .  . 
  .   .  . . .  .  .  .  . . . .  .   
  .   .  . . .  .  .  .  . . . .  .   
  @   @  . . .  .  .  .  . . . .  .   
 L0E  .  . . .  .  .  @  @ @ @ @  @   
  .   .  . . .  .  .  .  . . . .  .   
  .   .  . . .  .  .  .  . . . . L1W
  .   .  . . .  .  .  @  . G . .  .   
  .   .  . . .  .  .  @  @ @ @ @  @   
  .   .  . . .  .  .  .  . . . .  .   
  .   .  . . G  .  .  .  . . X X  .   
  .   .  . . .  .  .  .  . . X X  G"""
