world_string = """
. . . . . . . . . .  @ . . . . . . . . . X
. . . . . . . . . .  @ . . . . . . . . . X
. . . . . . . . . .  @ . . . . . . . . . X
. . . . . . . . . .  @ . . . . . . . . . X
. . . . . . . . . .  @ . . . . . . . . . X
. . . . . . . . . .  . . . . . . . . . . X
. . . . . . . . . .  @ . . . . . . . . . X
. . . . . . . . . .  @ . . . . . . . . . X
. . . . . . . . . .  @ . . . . . . . . . X
. . . . . . . . . .  @ . . . . . . . . . X
. . . . . . . . . .  @ . . . . . . . . . X
"""

[[agents]]
start_positions = [{ j_max = 9 }]

[[agents]]
start_positions = [{ j_max = 9 }]

[[agents]]
start_positions = [{ j_max = 9 }]

[[agents]]
start_positions = [{ j_max = 9 }]
