world_string = """
. . . . . . . . . .  @ . . . . . . . . . .
. . . . . . . . . .  @ . . . . . . . . . .
. . . . . . . . . .  @ . . . . . . . . . .
. . . . . . . . . .  @ . . . . . . . . . .
. . . . . . . . . .  @ . . . . . . . . . .
. . . . . . . . . .  . . . . . . . . . . .
. . . S0 . . . . . .  @ . . . . . . . . . .
. . . . . . . . . .  @ . . . . . . . . . .
. . . . . . . . . .  @ . . . . . . . . . .
. . . . . . . . . .  @ . . . . . . . . . .
. . . . . . . . . .  @ . . . . . . . . . X
"""

[[agents]]
start_positions = [{ j_max = 9 }]
