CREATE TABLE run(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created_at TEXT NOT NULL,
    seed INTEGER NOT NULL,
    meta_json TEXT
);


CREATE TABLE test(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    run INTEGER NOT NULL,
    timestamp TEXT NOT NULL,
    time_step INTEGER NOT NULL,
    seed INTEGER NOT NULL,
    FOREIGN KEY(run) REFERENCES run(id) ON DELETE CASCADE
);

CREATE TABLE test_metric(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    test INTEGER NOT NULL,
    key TEXT NOT NULL,
    value REAL NOT NULL,
    FOREIGN KEY(test) REFERENCES test(id) ON DELETE CASCADE
);

CREATE TABLE test_blob(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    test INTEGER NOT NULL,
    key TEXT NOT NULL,
    value BLOB NOT NULL,
    FOREIGN KEY(test) REFERENCES test(id) ON DELETE CASCADE
);
